import { College, Review } from "@/types";

export const MOCK_COLLEGES: College[] = [
  {
    id: "iit-bombay",
    name: "IIT Bombay",
    location: "Mumbai",
    state: "Maharashtra",
    type: "Government",
    established: 1958,
    ranking: 1,
    rating: 4.8,
    reviewCount: 1240,
    fees: { btech: 220000, mtech: 110000, mba: 250000 },
    placements: {
      averagePackage: 2100000,
      highestPackage: 12000000,
      placementRate: 98,
      topRecruiters: ["Google", "Microsoft", "Amazon", "Goldman Sachs", "McKinsey"],
    },
    courses: ["B.Tech", "M.Tech", "MBA", "PhD", "M.Sc"],
    facilities: ["Library", "Hostel", "Sports Complex", "Research Labs", "Canteen", "Medical Center"],
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    logo: "https://upload.wikimedia.org/wikipedia/en/1/1e/IIT_Bombay_Logo.svg",
    description: "IIT Bombay is one of the premier engineering institutions in India, known for its world-class research, innovation, and industry partnerships. Located in the heart of Mumbai, it has been consistently ranked as the top engineering college.",
    accreditation: ["NAAC A++", "NBA", "NIRF Rank 3"],
    website: "https://www.iitb.ac.in",
    phone: "+91-22-2572-2545",
    email: "admissions@iitb.ac.in",
  },
  {
    id: "iit-delhi",
    name: "IIT Delhi",
    location: "New Delhi",
    state: "Delhi",
    type: "Government",
    established: 1961,
    ranking: 2,
    rating: 4.7,
    reviewCount: 1100,
    fees: { btech: 215000, mtech: 105000, mba: 240000 },
    placements: {
      averagePackage: 2000000,
      highestPackage: 11500000,
      placementRate: 97,
      topRecruiters: ["Google", "Facebook", "Apple", "Morgan Stanley", "BCG"],
    },
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    facilities: ["Library", "Hostel", "Sports Ground", "Research Labs", "Canteen"],
    image: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800&q=80",
    logo: "https://upload.wikimedia.org/wikipedia/en/f/fd/Indian_Institute_of_Technology_Delhi_Logo.svg",
    description: "IIT Delhi is a public research university located in Hauz Khas, New Delhi. Known for its excellence in engineering and technology education, it consistently ranks among the top institutions in India.",
    accreditation: ["NAAC A++", "NBA", "NIRF Rank 2"],
    website: "https://home.iitd.ac.in",
    phone: "+91-11-2659-7135",
    email: "doaa@admin.iitd.ac.in",
  },
  {
    id: "nit-trichy",
    name: "NIT Trichy",
    location: "Tiruchirappalli",
    state: "Tamil Nadu",
    type: "Government",
    established: 1964,
    ranking: 8,
    rating: 4.5,
    reviewCount: 870,
    fees: { btech: 145000, mtech: 80000, mba: 160000 },
    placements: {
      averagePackage: 1400000,
      highestPackage: 7500000,
      placementRate: 95,
      topRecruiters: ["TCS", "Infosys", "Wipro", "Cognizant", "Samsung"],
    },
    courses: ["B.Tech", "M.Tech", "MBA", "MCA", "PhD"],
    facilities: ["Library", "Hostel", "Swimming Pool", "Labs", "Gym"],
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80",
    logo: "https://upload.wikimedia.org/wikipedia/en/5/51/National_Institute_of_Technology%2C_Tiruchirappalli_Logo.svg",
    description: "NIT Trichy is one of the oldest and most prestigious NITs in India. Located in Tamil Nadu, it offers excellent engineering programs with strong industry connections and placement records.",
    accreditation: ["NAAC A+", "NBA", "NIRF Rank 8"],
    website: "https://www.nitt.edu",
    phone: "+91-431-250-3000",
    email: "director@nitt.edu",
  },
  {
    id: "bits-pilani",
    name: "BITS Pilani",
    location: "Pilani",
    state: "Rajasthan",
    type: "Deemed",
    established: 1964,
    ranking: 12,
    rating: 4.6,
    reviewCount: 950,
    fees: { btech: 450000, mtech: 200000, mba: 380000 },
    placements: {
      averagePackage: 1800000,
      highestPackage: 10000000,
      placementRate: 96,
      topRecruiters: ["Microsoft", "Google", "Uber", "Flipkart", "Adobe"],
    },
    courses: ["B.Tech", "M.Tech", "MBA", "M.Sc", "PhD"],
    facilities: ["Library", "Hostel", "Sports Complex", "Labs", "Auditorium"],
    image: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&q=80",
    logo: "https://upload.wikimedia.org/wikipedia/en/d/d3/BITS_Pilani-Logo.svg",
    description: "BITS Pilani is a deemed university known for its practice school program, which provides students with real industry experience. It is one of the top private engineering institutions in India.",
    accreditation: ["NAAC A", "NBA", "NIRF Rank 27"],
    website: "https://www.bits-pilani.ac.in",
    phone: "+91-1596-242-192",
    email: "admissions@pilani.bits-pilani.ac.in",
  },
  {
    id: "vit-vellore",
    name: "VIT Vellore",
    location: "Vellore",
    state: "Tamil Nadu",
    type: "Deemed",
    established: 1984,
    ranking: 15,
    rating: 4.2,
    reviewCount: 2100,
    fees: { btech: 350000, mtech: 180000, mba: 300000 },
    placements: {
      averagePackage: 1200000,
      highestPackage: 8000000,
      placementRate: 92,
      topRecruiters: ["TCS", "Wipro", "Infosys", "Accenture", "Capgemini"],
    },
    courses: ["B.Tech", "M.Tech", "MBA", "MCA", "PhD"],
    facilities: ["Library", "Hostel", "Sports Ground", "Labs", "Shopping Mall"],
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80",
    logo: "https://upload.wikimedia.org/wikipedia/en/1/11/VIT_University_logo.png",
    description: "VIT Vellore is one of the largest private universities in India, known for its diverse student community, excellent infrastructure, and strong industry partnerships.",
    accreditation: ["NAAC A++", "NBA", "NIRF Rank 11"],
    website: "https://vit.ac.in",
    phone: "+91-416-220-2020",
    email: "ugadmission@vit.ac.in",
  },
  {
    id: "srm-chennai",
    name: "SRM Institute of Science and Technology",
    location: "Chennai",
    state: "Tamil Nadu",
    type: "Deemed",
    established: 1985,
    ranking: 28,
    rating: 4.0,
    reviewCount: 1800,
    fees: { btech: 320000, mtech: 160000, mba: 280000 },
    placements: {
      averagePackage: 1000000,
      highestPackage: 6500000,
      placementRate: 90,
      topRecruiters: ["TCS", "Infosys", "IBM", "Cognizant", "Dell"],
    },
    courses: ["B.Tech", "M.Tech", "MBA", "BBA", "PhD"],
    facilities: ["Library", "Hostel", "Cricket Ground", "Labs", "Auditorium"],
    image: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&q=80",
    logo: "https://upload.wikimedia.org/wikipedia/en/f/f6/SRM_Institute_of_Science_and_Technology_logo.png",
    description: "SRM Institute of Science and Technology is one of the largest private universities in India with a wide range of programs and excellent facilities.",
    accreditation: ["NAAC A++", "NBA", "NIRF Rank 36"],
    website: "https://www.srmist.edu.in",
    phone: "+91-44-2745-5510",
    email: "admissions@srmist.edu.in",
  },
  {
    id: "iit-madras",
    name: "IIT Madras",
    location: "Chennai",
    state: "Tamil Nadu",
    type: "Government",
    established: 1959,
    ranking: 3,
    rating: 4.9,
    reviewCount: 1350,
    fees: { btech: 225000, mtech: 115000, mba: 260000 },
    placements: {
      averagePackage: 2200000,
      highestPackage: 13000000,
      placementRate: 99,
      topRecruiters: ["Google", "Amazon", "Microsoft", "Apple", "Stripe"],
    },
    courses: ["B.Tech", "M.Tech", "MBA", "PhD", "M.Sc"],
    facilities: ["Library", "Hostel", "Deer Park", "Research Labs", "Olympic Pool"],
    image: "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800&q=80",
    logo: "https://upload.wikimedia.org/wikipedia/en/6/69/IIT_Madras_Logo.svg",
    description: "IIT Madras is India's top-ranked engineering institution, known for its beautiful campus set inside a national park, world-class research facilities, and exceptional placement records.",
    accreditation: ["NAAC A++", "NBA", "NIRF Rank 1"],
    website: "https://www.iitm.ac.in",
    phone: "+91-44-2257-8000",
    email: "admissions@iitm.ac.in",
  },
  {
    id: "manipal-university",
    name: "Manipal Institute of Technology",
    location: "Manipal",
    state: "Karnataka",
    type: "Deemed",
    established: 1957,
    ranking: 20,
    rating: 4.3,
    reviewCount: 1600,
    fees: { btech: 380000, mtech: 190000, mba: 340000 },
    placements: {
      averagePackage: 1300000,
      highestPackage: 7000000,
      placementRate: 91,
      topRecruiters: ["Infosys", "Wipro", "Amazon", "Accenture", "Deloitte"],
    },
    courses: ["B.Tech", "M.Tech", "MBA", "B.Arch", "PhD"],
    facilities: ["Library", "Hostel", "Hospital", "Sports Complex", "Beach Access"],
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80",
    logo: "https://upload.wikimedia.org/wikipedia/en/e/e8/Manipal_Institute_of_Technology_logo.jpg",
    description: "Manipal Institute of Technology is one of India's premier private engineering colleges, famous for its beautiful coastal campus and strong technical programs.",
    accreditation: ["NAAC A+", "NBA", "NIRF Rank 22"],
    website: "https://manipal.edu/mit.html",
    phone: "+91-820-292-5555",
    email: "mit.admissions@manipal.edu",
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "r1",
    collegeId: "iit-bombay",
    author: "Rahul Sharma",
    rating: 5,
    course: "B.Tech Computer Science",
    year: 2023,
    title: "Best engineering college in India",
    body: "IIT Bombay provided me with an incredible experience. The faculty is world-class, the research opportunities are unmatched, and the peer group you get is phenomenal. The placements are excellent and the campus life is vibrant.",
    pros: ["World-class faculty", "Excellent placements", "Great peer group", "Amazing research opportunities"],
    cons: ["Very competitive environment", "High stress", "Limited seats"],
    createdAt: "2023-12-15",
  },
  {
    id: "r2",
    collegeId: "iit-bombay",
    author: "Priya Patel",
    rating: 4,
    course: "M.Tech",
    year: 2022,
    title: "Great experience overall",
    body: "Spent 2 years here and it was transformative. The labs are top-notch and the industry exposure is excellent. Some professors are more research-oriented and not great teachers, but overall a great institution.",
    pros: ["Great labs", "Industry exposure", "Good stipends for M.Tech"],
    cons: ["Some professors not great at teaching", "High cost of living in Mumbai"],
    createdAt: "2022-08-10",
  },
  {
    id: "r3",
    collegeId: "nit-trichy",
    author: "Arun Kumar",
    rating: 5,
    course: "B.Tech Civil Engineering",
    year: 2023,
    title: "Excellent college with great facilities",
    body: "NIT Trichy is one of the best NITs in India. The faculty is excellent, the campus is beautiful, and the placement support is great. Highly recommend for engineering aspirants.",
    pros: ["Excellent faculty", "Great placement support", "Beautiful campus"],
    cons: ["Located in smaller city", "Limited entertainment options nearby"],
    createdAt: "2023-09-20",
  },
];

export const INDIAN_STATES = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh",
  "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand",
  "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur",
  "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan",
  "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh",
  "Uttarakhand", "West Bengal"
];

export const COURSE_OPTIONS = ["B.Tech", "M.Tech", "MBA", "MCA", "M.Sc", "PhD", "B.Arch", "BBA"];
